export enum EnvelopeBusMessageType {
  REQUEST_LANGUAGE,
  RETURN_LANGUAGE,

  REQUEST_GET_CONTENT,
  RETURN_GET_CONTENT,

  REQUEST_INIT,
  RETURN_INIT,

  REQUEST_SET_CONTENT,
  RETURN_SET_CONTENT
}
